const library_en = [
    "literally me",
    "litterally me",
    "lit rally me",
    "lit'rally me",
    "lit rallymi",
    "litrally me",
    "literaly me",
    "literallymee",
    "literly me",
    "litrly me",
    "literali me",
    "litterali me",
    "litrallymee",
    "literaly me",
    "litrelly me",
    "litteraly me",
    "literlly me",
    "litterallyme",
    "literelly me",
    "literaly me",
    "literaly me",
    "literraly me",
    "lit'rallyme",
    "me literally",
    "mi literally",
    "me litterally",
    "me lit'rally",
    "mee literally",
    "m literally",
    "me literal",
    "me literal-ly",
    "me lite rally",
    "me litrally",
    "me litterali",
    "me litterally",
    "me literrally",
    "me lit rally",
    "me lit'rally",
    "me lit rally",
    "me lit'rally",
    "me literallyy",
    "me literalyy",
    "me literali",
    "me litterly",
    "me lit rally",
    "me lit'rally",
    "he's literally me",
    "he's litterally me",
    "he's lit rally me",
    "he's lit'rally me",
    "he's lit rallymi",
    "he's litrally me",
    "he's literallymee",
    "he's literally me",
    "hes literally me",
    "he's lit rally",
    "he's litrally",
    "he's litterally",
    "he's literaly me",
    "he's literlly me",
    "he's litterallyme",
    "he's literelly me",
    "he's literaly me",
    "he's literaly me",
    "he's literraly me",
    "he's lit'rallyme",
    "hes litterally me",
    "he is literally me",
    "hes litteraly me",
    "he's literallymee",
    "i drive",
    "i drove",
    "drive i",
    "drove i",
];

const library_pt = [
    "eu dirijo",
    "eu dirige",
    "dirijo eu",
    "ele dirije",
    "ele dirige",
    "ela dirige",
    "eu draivo",
    "litralmente eu",
    "litramente eu",
    "litteralmente eu",
    "litralmete eu",
    "litralmeti eu",
    "literalmenti eu",
    "literalminte eu",
    "litrarmente eu",
    "literalmenti eu",
    "litrarmenti eu",
    "litrarmenti euzinha",
    "litralmente eu kkkk",
    "litralmente eu hahaha",
    "literaaaaaalmente eu",
    "litralmnte euzinha",
    "litralmenteu",
    "muito eu",
    "literalmente eu",
    "literau",
    "litralmenti u",
    "literalmenteu",
    "litralmenty",
    "litralment3",
    "literalm3nt3",
    "litramente eu rsrs",
    "literalmente eu kkk",
    "literalmenti euzinha",
    "literalmentchi eu",
    "litralmentchy eu",
    "literalmente eush",
    "litralmente euzitx",
    "literau eu",
    "litralmenti amigx",
    "ele é litralmente eu",
    "ele é litramente eu",
    "ele é litteralmente eu",
    "ele é litralmete eu",
    "ele é litralmeti eu",
    "ele é literalmenti eu",
    "ele é literalminte eu",
    "ele é litrarmente eu",
    "ele é literalmenti eu",
    "ele é litrarmenti eu",
    "ele é litrarmenti euzinha",
    "ele é litralmente eu kkkk",
    "ele é litralmente eu hahaha",
    "ele é literaaaaaalmente eu",
    "ele é litralmnte euzinha",
    "ele é litralmenteu",
    "ele é literau",
    "ele é litralmenti u",
    "ele é literalmenteu",
    "ele é litralmenty",
    "ele é litralment3",
    "ele é literalm3nt3",
    "ele é litramente eu rsrs",
    "ele é literalmente eu kkk",
    "ele é literalmenti euzinha",
    "ele é literalmentchi eu",
    "ele é litralmentchy eu",
    "ele é literalmente eush",
    "ele é litralmente euzitx",
    "ele é literau eu",
    "ele é litralmenti amigx",
    "eu litralmente",
    "eu litramente",
    "eu litteralmente",
    "eu litralmete",
    "eu litralmeti",
    "eu literalmenti",
    "eu literalminte",
    "eu litrarmente",
    "eu literalmenti",
    "eu litrarmenti",
    "eu litrarmenti euzinha",
    "eu litralmente kkkk",
    "eu litralmente hahaha",
    "eu literaaaaaalmente",
    "eu litralmnte euzinha",
    "eu litralmenteu",
    "eu literau",
    "eu litralmenti u",
    "eu literalmenteu",
    "eu litralmenty",
    "eu litralment3",
    "eu literalm3nt3",
    "eu litramente rsrs",
    "eu literalmente kkk",
    "eu literalmenti euzinha",
    "eu literalmentchi",
    "eu litralmentchy",
    "eu literalmente eush",
    "eu litralmente euzitx",
    "eu literau",
    "eu litralmenti amigx",
];

const denji = [
    "me fr fr",
    "just like me fr",
    "he like me",
    "he like me fr",
    "like me fr fr",
    "he just like me fr",
    "he just lik me fr",
    "he just lik meh fr",
    "he just like meh fr",
    "he jus like me fr",
    "he jus lik meh fr",
    "he just like meh fr",
    "he just like me for real",
    "he just lik meh for real",
    "he jus like meh for real",
    "he just lyk me fr",
    "he just lyke meh fr",
    "he jus lyk meh fr",
    "he just like me fr!!",
    "he just like me fr!!!",
    "he just like meh fr!!",
    "he just like me fr!!1",
    "he just like meh fr!!!",
    "he just like me fr!!1!1",
    "he just like me fr lol",
    "he just like meh fr lol",
    "he just lik me fr lol",
    "he just like me fr tbh",
    "he jus like meh fr tbh",
    "he just like me fr ngl",
    "he just like meh fr ngl",
    "he just like me fr fam",
    "he just like meh fr fam",
    "like me fr",
    "lik me fr",
    "lyk me fr",
    "like meh fr",
    "lik meh fr",
    "lyk meh fr",
    "like me for real",
    "lik meh for real",
    "lyk meh for real",
    "like me fr!",
    "like meh fr!!",
    "like me fr!!!",
    "like meh fr!!",
    "like me fr!!1",
    "like meh fr!!!1",
    "like me fr lol",
    "like meh fr lol",
    "like me fr tbh",
    "like meh fr tbh",
    "like me fr ngl",
    "like meh fr ngl",
    "like me fr fam",
    "like meh fr fam",
    "like me fr bruh",
    "like meh fr bruh",
    "like me fr 4real",
    "like meh fr 4real",
    "like me fr omg",
    "like meh fr omg",
    "he just like me",
    "he jus like me",
    "he just lik me",
    "he jus lik me",
    "he just like meh",
    "he jus like meh",
    "he just like meh lol",
    "he just lik meh lol",
    "he jus lik meh lol",
    "he just lyk me",
    "he jus lyk me",
    "he just like me fr",
    "he jus like me fr",
    "he just lik me fr",
    "he jus lik me fr",
    "he just like me 4real",
    "he jus like me 4real",
    "he just lik me 4real",
    "he jus lik me 4real",
    "he just like me tbh",
    "he jus like me tbh",
    "he just lik me tbh",
    "he jus lik me tbh",
    "he just like meh tbh",
    "he jus like meh tbh",
    "he just lik meh tbh",
    "he jus lik meh tbh",
    "he just like me omg",
    "he jus like me omg",
    "he just lik me omg",
    "he jus lik me omg"
];

exports.library_en = library_en;
exports.library_pt = library_pt;
exports.denji = denji;